# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'image restoration
#'
#'@param M the grayscale matrix with some elements missing
#'@param lambda the shrinkage parameter 
#'@param delta an upper bound of the second-order gradient of the 
#'first part of the optimization function
#'@param stepsize Acceleration parameter
#'@return the reconstructed matrix
#'@example 
#'require(accProImageRestoration)
#'img=matrix(runif(1000,0,1),nrow=20)
#'ratio=0.4
#'randomMissfun=function(X,ratio,replace){
#'m=nrow(X)
#'n=ncol(X)
#'A=matrix(runif(m*n,0,1),ncol=n)
#'ind=which(A<=ratio)
#'vecX=c(X)
#'vecX[ind]=replace
#'X=matrix(vecX,ncol=n)
#'return(X)
#'}
#'M=randomMissfun(img,ratio,1.001)
#'lambda=0.1
#'delta=1
#'stepsize=0.5
#'softThresholdOperator(M,lambda,delta,0.5)
accProImageRestoration <- function(M, lambda, delta, stepSize) {
    .Call('_imageRestoration_accProImageRestoration', PACKAGE = 'imageRestoration', M, lambda, delta, stepSize)
}

#'optimization problem: $\frac{1}{2}||Y-X||^2_F+\lambda||Y||_{S_1}$
#'
#'@param X the known matrix in the optimization problem
#'@param lambda the shrinkage parameter 
#'@return the optimal solution of the problem
#'@example
#'require(softThresholdOperator)
#'X=matrix(runif(20,0,1),nrow=4)
#'lambda=0.1
#'softThresholdOperator(X,lambda)
softThresholdOperator <- function(X, lambda) {
    .Call('_imageRestoration_softThresholdOperator', PACKAGE = 'imageRestoration', X, lambda)
}

